#!/bin/bash
bubble_sort() {
    local arr=("$@")
    local n=${#arr[@]}
    for ((i=0; i<n; i++)); do
        for ((j=0; j<n-i-1; j++)); do
            if [[ "${arr[j]}" > "${arr[j+1]}" ]]; then
                temp="${arr[j]}"
                arr[j]="${arr[j+1]}"
                arr[j+1]="$temp"
            fi
        done
    done
    echo "${arr[@]}"
}

remove_duplicates() {
    local arr=("$@")
    local unique=()
    local seen=""
    
    for item in "${arr[@]}"; do
        if [[ ! " $seen " =~ " $item " ]]; then
            unique+=("$item")
            seen="$seen $item"
        fi
    done
    
    echo "${unique[@]}"
}

options=()
isValidInputOutput=true

while getopts ":abcedfghi:jklmno:pqrstuwvxyz" arg; do
    case $arg in
        i)
            if [[ "$OPTARG" == -* ]]; then
                isValidInputOutput=false
            else
                options+=("i")
                inputFile="$OPTARG"
            fi
            ;;
        o)
            if [[ "$OPTARG" == -* ]]; then
                isValidInputOutput=false
            else
                options+=("o")
                outputFile="$OPTARG"
            fi
            ;;
        q)
            echo "Unsupported option: -q"
            exit 0
            ;;
        :)
            isValidInputOutput=false
            ;;
        *)
            options+=("$arg")
            ;;
    esac
done

if [ "$isValidInputOutput" = false ]; then
    echo "-i -o options require a filename"
    exit 0
else
    options=($(remove_duplicates "${options[@]}"))
    options=($(bubble_sort "${options[@]}"))
    
    for opt in "${options[@]}"; do
        if [ "$opt" = "i" ]; then
            result="-i present and set to \"$inputFile\""
            echo "$result"
        elif [ "$opt" = "o" ]; then
            result="-o present and set to \"$outputFile\""
            echo "$result"
        else
            result="-$opt present"
            echo "$result"
        fi
    done
fi

shift $((OPTIND-1))

if [ $# -eq 0 ]; then
    exit 0
else
    echo "Arguments are:"
    for i in $(seq 1 $#); do
        eval "echo '$'\${i}=\${$i}"
    done
fi

exit 0